apiVersion: arcdata.microsoft.com/v1beta1
kind: ActiveDirectoryConnector
metadata:
  name: adarc
  namespace: arc
spec:
  activeDirectory:
    realm: CONTOSO.LOCAL .
    netbiosDomainName: CONTOSO 
    domainControllers:
      primaryDomainController:
        hostname: azdc01.contoso.local 
  dns:
    preferK8sDnsForPtrLookups: false
    nameserverIPAddresses:
      - 10.10.10.11