apiVersion: v1
data:
  password: UHVrb245MDA=
  username: YXJjYWRtaW4= 
kind: Secret
metadata:
  name: arcadmin-login-secret
  namespace: arc-auto-ad 
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v3
kind: SqlManagedInstance
metadata:
  name: sql-ad-mi
  namespace: arc-auto-ad 
spec:
  backup:
    retentionPeriodInDays: 7
  dev: true
  tier: GeneralPurpose
  forceHA: "true"
  licenseType: LicenseIncluded
  replicas: 1
  scheduling:
    default:
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
  security:
    adminLoginSecret: arcadmin-login-secret
    activeDirectory:
      connector:
        name: adarc
        namespace: arc-auto-ad 
      accountName: arcsqluser
  services:
    primary:
      type: LoadBalancer
      dnsName: azdc.contoso.local
      port: 31433
  storage:
    backups:
      volumes:
        - className: default
          size: 5Gi
    data:
      volumes:
        - className: default
          size: 5Gi
    datalogs:
      volumes:
        - className: default
          size: 5Gi
    logs:
      volumes:
        - className: default
          size: 5Gi